### PR TITLE
Migrating database to PostgreSQL

### LINKED ISSUE #175: Migrate the database to PostgreSQL
**Is your feature request related to a problem? Please describe.**
In the deployed version in heroku, we are using cleardb MySQL for the database, but there's a query limit. So its better to use heroku postgresql to keep the database(only for the deployment)

**Describe the solution you'd like**
Update the configuration to work wit postgres plugin which comes with heroku

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Piumal1999**
## Purpose

The purpose of this PR is to fix #175 

## Goals

Updating the configuration to work with postgresql database

## Approach

Updated the configuration.
Syntaxes are same, so no need to update the custom queries.

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
 
N/A

## Test environment
 
MacOS Big Sur
Google Chrome

## Learning

N/A

**Branch : Deployment**

### CODE REVIEW

**Review by anjula-sack — APPROVED** [review]

**Review by Gravewalker666 — APPROVED** [review]
Nice @Piumal1999 
Did you check this out local?

**Comment by Piumal1999** [comment]
> Nice @Piumal1999
> Did you check this out local?

I checked the login scenario. The user profile was created properly. 
But didn't check the delete mentee scenario. I just compared the syntaxes of custom queries and they were same in PostgreSQL and MySQL

**Comment by Gravewalker666** [comment]
> 
> I checked the login scenario. The user profile was created properly.
> But didn't check the delete mentee scenario. I just compared the syntaxes of custom queries and they were same in PostgreSQL and MySQL

Awesome, I'll work without a hassle then

**Comment by Piumal1999** [comment]
fixes #176

**Pull request merged**
