### PR TITLE
Update user API to get the user's id from the session

### LINKED ISSUE #72: Update the endpoints to get profile id from the session
**Is your feature request related to a problem? Please describe.**
For user APIs, we need to get the user's profile from the session

**Describe the solution you'd like**
Get the profileId from a cookie

**Describe alternatives you've considered**
N/A

**Additional context**
Hive thread:
https://sef.discourse.group/t/creating-mock-user-apis/207?u=piumal1999

### LINKED ISSUE #79: API to get user's mentoring programs
**Is your feature request related to a problem? Please describe.**
An API to get logged in user's mentoring programs

**Describe the solution you'd like**
```
GET me/programs/mentoring
Cookie: user-id
Response: List<Program>
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### LINKED ISSUE #80: API to get user's menteeing programs
**Is your feature request related to a problem? Please describe.**
An API to get logged in user's menteeing programs

**Describe the solution you'd like**
```
GET me/programs/menteeing
Cookie: user-id
Response: List<Program>
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Piumal1999**
## Purpose

The purpose of this PR is to fix #72  fix #79  fix #80 

## Goals

Getting the user Id from a cookie in the session
Add an endpoint to get the current user's profile
Add an endpoint to get current user's menteeing programs
Add an endpoint to get current user's mentoring programs

## Approach

Used @CookieValue annotation
Added the endpoints with unit tests

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 
N/A

## Test environment
 
Ubuntu 19.04
OpenJDK 1.8
Google Chrome

## Learning

N/A

### CODE REVIEW

**Review by YohanAvishke — COMMENTED** [review]
Good job @Piumal1999. But I have few questions,
1. How the cookie is created? 
1. Shouldn't there be an API that's invoked when a user log-in which will create the cookie.
1. How the browser will know user's profile id? 
1. Shouldn't there be an API for users to get their profile(filtered by email or some other param)?

**Comment by Piumal1999** [comment]
Added 2 new Endpoints. 
1. To get current user's mentoring programs
2. To get the current user's menteeing programs

**Comment by jayasanka-sack** [comment]
@YohanAvishke can we get this merged?

**Review by YohanAvishke — APPROVED** [review]
AWSOME JOB @Piumal1999 👏

**Pull request merged**
