### PR TITLE
Add delete mentee statement to MenteeService.java

### LINKED ISSUE #166: Add delete mentee statement to MenteeService.java
**Describe the bug**
- As suggested by Piumal, the delete mentee statement hasn't been declared in MenteeService.java.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to MenteeService.java
2. Scroll down to the `deleteMentee` method.
3. Add `menteeRepository.deleteById(id);` to the end of the method

**Desktop (please complete the following information):**
 - OS: macOS BigSur 
 - Browser Safari
 - Version 14.0.1

### PR DESCRIPTION
**Pull request by kumuditha-udayanga**
## Purpose

The purpose of this PR is to fix #166

## Goals

- Declare delete statement to MenteeService.java `deleteMentee` method.

## Approach

1. Go to MenteeService.java
2. Scroll down to the `deleteMentee` method.
3. Add `menteeRepository.deleteById(id);` to the end of the method

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
 
- OS: macOS BigSur
- Browser: Safari
- IDE: IntelliJ IDEA

### CODE REVIEW

**Review by Piumal1999 — APPROVED** [review]
Good job @kumuditha-udayanga

**Review by Gravewalker666 — APPROVED** [review]
Looks good @kumuditha-udayanga 
Did you test this out??

**Comment by kumuditha-udayanga** [comment]
> Looks good @kumuditha-udayanga
> Did you test this out??

Yeah, the front-end mentee delete option worked once this was added. 
https://github.com/sef-global/scholarx-frontend/pull/181

**Comment by Gravewalker666** [comment]
Nice

**Pull request merged**
