### PR TITLE
Make programs endpoints public

### LINKED ISSUE #121: Make programs endpoints public
**Is your feature request related to a problem? Please describe.**
Currently, the security configurations are set to permit all for `api/programs` endpoint, but it is required to make all the `program` endpoints to be public not just `api/programs`

**Describe the solution you'd like**
Change `api/programs` into `api/program/**` in the security config file

### PR DESCRIPTION
**Pull request by Gravewalker666**
## Purpose

The purpose of this PR is to fix #121 

## Goals

- To make programs endpoints public

## Approach
- Changed `api/programs` antMatcher into `api/program/**`

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Test environment
- Postman
- macOS Big Sur

## Learning
- https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html

### CODE REVIEW

**Review by Piumal1999 — APPROVED** [review]
Good job @Gravewalker666 
Btw, now the endpoints like 'apply as mentor' endpoint are also public. Do we restrict it later?

**Comment by Gravewalker666** [comment]
@Piumal1999 Ah yeah, I missed it, my bad
It's just a matter of adding another `antMatcher` pattern right?
I'll fix that and update the PR. 
Thank you

**Comment by Piumal1999** [comment]
> @Piumal1999 Ah yeah, I missed it, my bad
> It's just a matter of adding another `antMatcher` pattern right?
> I'll fix that and update the PR. 
> Thank you

Yeah. That's good. Thank you

**Comment by Gravewalker666** [comment]
@Piumal1999 could you please take another look? PR is updated

**Review by Piumal1999 — APPROVED** [review]
Thanks you @Gravewalker666

**Pull request merged**
