### PR TITLE
Change build configuration to switch from webpack development mode to production mode

### LINKED ISSUE #155: Scholarx application takes so much time to load
**Describe the bug**
- `Bundle.js` file generated from the build script is too much. Due to this, the application takes much more time to load.

**To Reproduce**
- Change the Webpack configuration in the build script to reduce the file size.

**Screenshots**
Image from iOS

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Google Chrome
 - Version 90.0.4430.93 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by Gimhan-minion**
## Purpose

The purpose of this PR is to fix #155 

## Goals
- To reduce scholarx application loading rime

## Approach
- Switch from webpack development mode to webpack production mode in order to reduce file size.

### Screenshots
Screenshot from 2021-06-04 19-36-40
  
##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by jayasanka-sack — CHANGES_REQUESTED** [review]
Gimhan, this seems hacky. I think we need to change the build script of the package json.

**Comment by Gimhan-minion** [comment]
> Gimhan, this seems hacky. I think we need to change the build script of the package json.

Sure! Let me close this PR and create a separate one on the frontend repo 😃

**Comment by jayasanka-sack** [comment]
This will reduce the file size of the webpack dev server (which we run locally). 
The problem is the Travis build script is not using the start script when we deploy the frontend. It uses the `build` (`npm run build`) script.

**Comment by jayasanka-sack** [comment]
However, the build script is already configured to build a production version. 
This article might help to find a solution:
https://blog.jakoblind.no/3-ways-to-reduce-webpack-bundle-size/

**Pull request closed without merging**
